apiVersion: v1 
kind: Secret    
metadata:           # meta deta used for defining the of naming
  name: mongodb-secret
type: Opaque               # key value secret type
data:  # below values are base 64 decodeds
    mongo-root-username: dXNlcm5hbWU= # how to generate base 64 in linux terminals echo -n 'THING_TO_CONVERT' | base6
    mongo-root-password: cGFzc3dvcmQ=
    # kubectl apply -f mongodb_secrets.yaml
    # kubectl get secret