apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment    
metadata:           # meta deta used for defining the of naming
  name: mongodb-deployment
  labels:
    app: mongodb  
spec:               # specs for you kind here deployment
  selector:
    matchLabels:
      app: mongodb
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # used for pods create pods using pod definition in this template
    metadata:
      labels:
        app: mongodb  # all the pods created using this blue print will be labeled as app nginx
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env: # setting env variables since we dont want to add value we use secrets
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: # refeerencing secret values from
             secretKeyRef: # reference of secret files
               name: mongodb-secret # name used in mongo_secret
               key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: # refeerencing secret values from
             secretKeyRef: # reference of secret files
               name: mongodb-secret # name used in mongo_secret
               key: mongo-root-password
                 # kubectl apply -f mongodb_deployment.yaml
                 # kubectl get secret