apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Service    
metadata:           # meta deta used for defining the of naming
  name: mongo-express-service
  labels:
    app: mongo-express      # lable is pointer to labels in deployment yaml file   
spec:               # specs for you kind here deployment
  selector:
    app: mongo-express # this selector should match the label of pod in deployments template-metadata--labels-app
  type: LoadBalancer   # accepts external req by assigning this serevice external IP ->minikube service mongo-express-service
  ports:
    - protocol: TCP
      port: 8081  # service port
      targetPort: 8081  # port of pod should match the port in deployment container port containers-ports-containerPort
      nodePort: 30000  # exposes external IP address will be open port range-> 30000-32000 to be open in browser



# kubectl apply -f mongodb_service.yaml        
# check if service is mapped with correct pod or not
# kubectl describe service mongodb-service
# kubectl get pod -o wide
# and than check the ip of pod and service

# to start this 
# first make config maps
# start databse mondodb
# startmonog express
