apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment    
metadata:           # meta deta used for defining the of naming
  name: nginx-deployment
  labels:
    app: nginx  
spec:               # specs for you kind here deployment
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # used for pods create pods using pod definition in this template
    metadata:
      labels:
        app: nginx  # all the pods created using this blue print will be labeled as app nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080